[package]
name = "myelin-neural-network"
description = "Neural networks and their components"
version = "0.1.0"
authors = ["Jan Nils Ferner <jan@myelin.ch>"]
edition = "2018"

[dependencies]
mockiato = { git = "https://github.com/myelin-ai/mockiato", optional = true }
myelin-environment = { path = "../environment" }
myelin-geometry = { path = "../geometry" }
slab = "0.4"

[dev-dependencies]
maplit = "1.0"
myelin-environment = { path = "../environment", features = ["use-mocks"] }
mockiato = { git = "https://github.com/myelin-ai/mockiato" }

[features]
use-mocks = ["mockiato"]
