[package]
name = "myelin-neural-network"
description = "Neural networks and their components"
version = "0.1.0"
authors = ["Jan Nils Ferner <jan@myelin.ch>"]
edition = "2018"

[dependencies]
mockiato = { git = "https://github.com/myelin-ai/mockiato", optional = true }
myelin-engine = { git = "https://github.com/myelin-ai/engine" }
myelin-geometry = { git = "https://github.com/myelin-ai/engine" }
slab = "0.4"

[dev-dependencies]
maplit = "1.0"
myelin-engine = { git = "https://github.com/myelin-ai/engine", features = ["use-mocks"] }
mockiato = { git = "https://github.com/myelin-ai/mockiato" }

[features]
use-mocks = ["mockiato"]
