[workspace]
members = [
    "visualization-core",
    "visualization-client",
    "visualization-server",
    "worldgen",
    "object-behavior",
    "object-data",
    "random",
    "neural-network",
    "clone-box",
    "genetics",
    "associate-lists",
]
