[package]
name = "myelin-worldgen"
version = "0.1.0"
authors = [
    "Jan Nils Ferner <jan@myelin.ch>",
    "Mathias Fischler <mathias@myelin.ch>",
    "Ruben Schmidmeister <ruben@myelin.ch>",
    "Jeremy Stucki <jeremy@myelin.ch>",
]
edition = "2018"

[dependencies]
myelin-environment = { path = "../environment" }
myelin-geometry = { path = "../geometry" }
myelin-object-data = { path = "../object-data" }
nameof = "0.1"
rand = "0.6.1"

[dev-dependencies]
myelin-object-behavior = { path = "../object-behavior" }
mockiato = { git = "https://github.com/myelin-ai/mockiato" }
myelin-environment = { path = "../environment", features = ["use-mocks"] }
